package com.tony.demo.infra.init;

import java.time.LocalDate;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.CommandLineRunner;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import com.tony.demo.modules.user.domain.User;
import com.tony.demo.modules.user.domain.UserRepository;
import com.tony.demo.modules.user.domain.UserStatus;
import com.tony.demo.modules.account.domain.Account;
import com.tony.demo.modules.account.domain.AccountRepository;
import com.tony.demo.modules.account.domain.AccountStatus;
import java.math.BigDecimal;
import java.util.UUID;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

@Component
@RequiredArgsConstructor
@Slf4j
public class FakeCustomerSeeder implements CommandLineRunner {

    private final UserRepository userRepository;
    private final AccountRepository accountRepository;
    private final PasswordEncoder passwordEncoder;

    @Value("${fake.customer.username}")
    private String username;

    @Value("${fake.customer.fullName}")
    private String fullName;

    @Value("${fake.customer.dob}")
    private String dob;

    @Value("${fake.customer.email}")
    private String email;

    @Value("${fake.customer.password}")
    private String password;

    @Value("${fake.customer.phone}")
    private String phone;

    @Value("${fake.customer.identity}")
    private String identity;

    @Value("${fake.customer.kycStatus}")
    private String kycStatus;

    @Override
    @Transactional
    public void run(String... args) throws Exception {
        if (!userRepository.existsByUsername(username)) {
            log.info("Inserting fake customer {} from environment variables...", username);
            User user = User.builder()
                    .username(username)
                    .fullName(fullName.replace("\"", "")) // Clean up quotes if present
                    .dateOfBirth(LocalDate.parse(dob))
                    .email(email)
                    .password(passwordEncoder.encode(password)) // Hash password
                    .phoneNumber(phone)
                    .identityNumber(identity)
                    .kycStatus(UserStatus.VERIFIED) // Force VERIFIED for testing easily
                    .build();
            // id, public_id are generated by sequences and BaseEntity automatically
            userRepository.save(user);

            Account account = Account.builder()
                    .userId(user.getId())
                    .accountNumber(UUID.randomUUID().toString().replaceAll("-", "").substring(0, 10).toUpperCase())
                    .balance(new BigDecimal("5000000"))
                    .currency("VND")
                    .status(AccountStatus.ACTIVE)
                    .build();
            accountRepository.save(account);

            log.info("Fake customer {} inserted successfully with 5,000,000 VND and ACTIVE account.", username);
        } else {
            log.info("Fake customer {} already exists in database.", username);
        }
    }
}
